server:
  host: 0.0.0.0
  port: 8080
  mode: debug
  useGinLogger: true
  middleWares:
    - MiddleWareCommon
  validators:
  groups:
    - prefix: /api/v1
      middleWares:
        - MiddleWareV1
      apis:
        - route: get /demo1
          handlers:
            - V1Demo1
        - route: get /demo2
          handlers:
            - V1Demo2
    - prefix: /api/v2
      middleWares:
        - MiddleWareV2
      apis:
        - route: get /demo1
          handlers:
            - V2Demo1
        - route: get /demo2
          handlers:
            - V2Demo2
      groups:
        - prefix: /sub
          middleWares:
            - MiddleWareV2
          apis:
            - route: get /v1
              handlers:
                - V2V1Demo1
            - route: get /v2
              handlers:
                - V2V1Demo2
